/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stocks` | `/stocks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/richCircle` | `/richCircle`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/poorCircle` | `/poorCircle`; params?: Router.UnknownInputParams; } | { pathname: `/create-user/user-info`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/stocks` | `/stocks`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/richCircle` | `/richCircle`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/poorCircle` | `/poorCircle`; params?: Router.UnknownOutputParams; } | { pathname: `/create-user/user-info`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/stocks${`?${string}` | `#${string}` | ''}` | `/stocks${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/richCircle${`?${string}` | `#${string}` | ''}` | `/richCircle${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/poorCircle${`?${string}` | `#${string}` | ''}` | `/poorCircle${`?${string}` | `#${string}` | ''}` | `/create-user/user-info${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stocks` | `/stocks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/richCircle` | `/richCircle`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/poorCircle` | `/poorCircle`; params?: Router.UnknownInputParams; } | { pathname: `/create-user/user-info`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
